version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: database
      DB_NAME: cashFlowManager_DB
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: teste
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: cashFlowManager_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend